trigger:
- main  # El nombre de la rama que activará el pipeline

pool:
  vmImage: 'ubuntu-latest'

variables:
  sshConnection: 'user@your-vm-ip'  # Reemplaza con tu usuario y la IP de la VM
  sshKey: $(sshKey)  # Variable secreta configurada en Azure DevOps con tu clave SSH

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'SSH Service Connection'
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: '**'
    targetFolder: '/home/user/app'  # Directorio en la VM
    cleanTargetFolder: true
    overwrite: true

- task: SSH@0
  inputs:
    sshEndpoint: 'SSH Service Connection'
    runOptions: 'inline'
    inline: |
      cd /home/user/app
      # Comandos para iniciar la aplicación, por ejemplo:
      docker-compose up -d
  displayName: 'Deploy application'
